name: build
on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        target: [win-x64, linux-x64, osx-x64, osx-arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('bun.lockb') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun i
      - name: Build
        run: bun run build -- ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: build
